title: Sketchbook
author:
  name: ridlees
paginate: 5
description: > # this means to ignore newlines until "show_excerpts:"
 Mostly Martin's sketchbook - or zettelkasten but for shitposting.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: kapesniP
    github:  ridlees
theme: minima

plugins:
 - jekyll-feed